name: Build VSIX and Upload Artifact

on:
  workflow_dispatch:
  push:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install global dependencies
        run: |
          npm install -g typescript prettier eslint vsce

      - name: Install project dependencies
        run: npm install

      - name: Build .vsix package
        run: npm run build

      - name: Find .vsix file
        id: get_vsix
        run: |
          VSIX_PATH=$(find . -name "*.vsix" | head -n 1)
          echo "Found VSIX at $VSIX_PATH"
          echo "vsix_path=$VSIX_PATH" >> $GITHUB_OUTPUT

      - name: Upload .vsix as artifact
        uses: actions/upload-artifact@v3
        with:
          name: vscode-extension
          path: ${{ steps.get_vsix.outputs.vsix_path }}
